name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: /node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install
      - name: Set Environment Variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> $GITHUB_ENV
          echo "REFRESH_TOKEN_EXPIRES_IN=${{ secrets.REFRESH_TOKEN_EXPIRES_IN }}" >> $GITHUB_ENV
      - name: Add node_modules/.bin to PATH using Environment File
        run: echo "PATH=$(npm prefix)/node_modules/.bin:$PATH" >> $GITHUB_ENV
      - name: Run Tests
        run: npm run test